version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.6
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm test
  lint:
    docker:
      - image: circleci/node:12.6
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test
      - lint
