version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  lint-build-test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - sonarcloud/scan

workflows:
  version: 2
  main-workflow:
    jobs:
      - lint-build-test:
          context: SonarCloud
